// lib/exportPdf.ts
// Clean text-only academic report — no graphics, no charts, no UI capture.
// Transcript-style layout using jsPDF text primitives only.

import type { DashboardStore } from "@/lib/utils";
import { getLetterGrade, formatRelativeTime } from "@/lib/utils";

// ── Page constants ────────────────────────────────────────────────────────────
const PAGE_W  = 210;          // A4 mm
const PAGE_H  = 297;
const ML      = 25;           // left margin
const MR      = PAGE_W - 25; // right margin
const BOTTOM  = PAGE_H - 20; // footer threshold

// ── Colours: monochrome for transcript feel ───────────────────────────────────
const BLACK  : [number,number,number] = [0,   0,   0  ];
const DARK   : [number,number,number] = [30,  30,  30 ];
const MID    : [number,number,number] = [90,  90,  90 ];
const LIGHT  : [number,number,number] = [160, 160, 160];
const WHITE  : [number,number,number] = [255, 255, 255];

// ── Trend label (plain text) ──────────────────────────────────────────────────
function trendLabel(semesters: DashboardStore["semesters"]): string {
  if (semesters.length < 2) return "N/A (insufficient data)";
  const sorted = [...semesters].sort((a, b) =>
    a.name.localeCompare(b.name, undefined, { numeric: true })
  );
  const diff = sorted[sorted.length - 1].gpa - sorted[sorted.length - 2].gpa;
  if (diff > 0.05)  return `Improving  (+${diff.toFixed(2)} from last semester)`;
  if (diff < -0.05) return `Dropping   (${diff.toFixed(2)} from last semester)`;
  return `Stable     (${diff >= 0 ? "+" : ""}${diff.toFixed(2)} from last semester)`;
}

// ── Letter grade (short) ──────────────────────────────────────────────────────
function shortGrade(gpa: number): string {
  if (gpa >= 3.7) return "A";
  if (gpa >= 3.3) return "A-";
  if (gpa >= 3.0) return "B+";
  if (gpa >= 2.7) return "B";
  if (gpa >= 2.3) return "B-";
  if (gpa >= 2.0) return "C+";
  if (gpa >= 1.7) return "C";
  return "F";
}

// ── Main export ───────────────────────────────────────────────────────────────
export async function exportDashboardPdf(store: DashboardStore): Promise<void> {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const sems = [...store.semesters].sort((a, b) =>
    a.name.localeCompare(b.name, undefined, { numeric: true })
  );

  const cgpa =
    sems.length > 0
      ? sems.reduce((s, sem) => s + sem.gpa * sem.totalCredits, 0) /
        sems.reduce((s, sem) => s + sem.totalCredits, 0)
      : null;
  const totalCredits = sems.reduce((s, sem) => s + sem.totalCredits, 0);

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  // ── State: cursor y, page number ──────────────────────────────────────────
  let y    = 0;
  let page = 1;

  // ── Low-level helpers ─────────────────────────────────────────────────────

  function newPage() {
    drawFooter();
    doc.addPage();
    page += 1;
    y = 20;
  }

  function guard(needed: number) {
    if (y + needed > BOTTOM) newPage();
  }

  function drawFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(LIGHT[0], LIGHT[1], LIGHT[2]);
    // Thin rule
    doc.setDrawColor(LIGHT[0], LIGHT[1], LIGHT[2]);
    doc.setLineWidth(0.3);
    doc.line(ML, PAGE_H - 16, MR, PAGE_H - 16);
    doc.text("Generated by GradeIQ", ML, PAGE_H - 11);
    doc.text(`Page ${page}`, MR, PAGE_H - 11, { align: "right" });
    // Reset
    doc.setTextColor(DARK[0], DARK[1], DARK[2]);
  }

  function rule(thickness = 0.3, color: [number,number,number] = DARK) {
    doc.setDrawColor(color[0], color[1], color[2]);
    doc.setLineWidth(thickness);
    doc.line(ML, y, MR, y);
  }

  function gap(mm: number) { y += mm; }

  function text(
    str: string,
    x: number,
    opts: {
      size?: number;
      bold?: boolean;
      color?: [number,number,number];
      align?: "left" | "right" | "center";
    } = {}
  ) {
    const { size = 10, bold = false, color = DARK, align = "left" } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(str, x, y, { align });
  }

  function row(left: string, right: string, labelSize = 10) {
    text(left,  ML,   { size: labelSize });
    text(right, MR,   { size: labelSize, align: "right" });
    gap(6);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 1
  // ═══════════════════════════════════════════════════════════════════════════
  y = 24;

  // ── INSTITUTION HEADER ────────────────────────────────────────────────────
  text("GradeIQ", PAGE_W / 2, { size: 22, bold: true, color: BLACK, align: "center" });
  gap(7);
  text("Academic Performance Report", PAGE_W / 2, { size: 11, color: MID, align: "center" });
  gap(3);
  text("gradeiq.app", PAGE_W / 2, { size: 8, color: LIGHT, align: "center" });
  gap(8);

  // Heavy rule under title
  rule(0.8, BLACK);
  gap(7);

  // ── STUDENT INFORMATION ───────────────────────────────────────────────────
  text("STUDENT INFORMATION", ML, { size: 7.5, bold: true, color: LIGHT });
  gap(5);
  row(`Student Name:   ${store.userName || "—"}`,         `Date Issued:  ${today}`);
  row(`Report ID:      ${Date.now().toString(36).toUpperCase()}`, "");
  gap(2);
  rule(0.3);
  gap(7);

  // ── ACADEMIC SUMMARY ──────────────────────────────────────────────────────
  text("ACADEMIC SUMMARY", ML, { size: 7.5, bold: true, color: LIGHT });
  gap(5);

  row(
    `Cumulative GPA (CGPA):`,
    cgpa !== null ? `${cgpa.toFixed(3)}  /  4.000` : "—"
  );
  row(
    `Academic Standing:`,
    cgpa !== null ? getLetterGrade(cgpa) : "—"
  );
  row(
    `Performance Trend:`,
    trendLabel(sems)
  );
  row(
    `Total Semesters Completed:`,
    String(sems.length)
  );
  row(
    `Total Credit Hours Earned:`,
    String(totalCredits)
  );
  if (store.targetGPA) {
    row(
      `Target CGPA:`,
      `${store.targetGPA.toFixed(2)}  —  ${
        cgpa !== null && cgpa >= store.targetGPA
          ? "Goal Achieved"
          : cgpa !== null
          ? `${(store.targetGPA - cgpa).toFixed(2)} pts remaining`
          : "—"
      }`
    );
  }

  gap(2);
  rule(0.3);
  gap(7);

  // ── SEMESTER BREAKDOWN ────────────────────────────────────────────────────
  text("SEMESTER BREAKDOWN", ML, { size: 7.5, bold: true, color: LIGHT });
  gap(5);

  if (sems.length === 0) {
    text("No semesters have been saved yet.", ML, { size: 10, color: MID });
    gap(6);
  } else {
    // Column positions
    const COL_NAME    = ML;
    const COL_GPA     = ML + 90;
    const COL_GRADE   = ML + 115;
    const COL_CREDITS = ML + 135;
    const COL_SAVED   = MR;

    // Column header row
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(MID[0], MID[1], MID[2]);
    doc.text("Semester",      COL_NAME,    y);
    doc.text("GPA",           COL_GPA,     y);
    doc.text("Grade",         COL_GRADE,   y);
    doc.text("Credits",       COL_CREDITS, y);
    doc.text("Saved",         COL_SAVED,   y, { align: "right" });
    gap(3);

    // Thin rule under column headers
    rule(0.2, MID);
    gap(4.5);

    // Data rows
    sems.forEach((sem, i) => {
      guard(7);

      doc.setFont("helvetica", i % 2 === 0 ? "normal" : "normal");
      doc.setFontSize(10);
      doc.setTextColor(DARK[0], DARK[1], DARK[2]);
      doc.text(sem.name, COL_NAME, y);

      doc.setFont("helvetica", "bold");
      doc.text(sem.gpa.toFixed(2), COL_GPA, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(MID[0], MID[1], MID[2]);
      doc.text(shortGrade(sem.gpa),         COL_GRADE,   y);
      doc.text(String(sem.totalCredits),    COL_CREDITS, y);
      doc.text(formatRelativeTime(sem.savedAt), COL_SAVED, y, { align: "right" });

      gap(6.5);

      // Light separator between rows (not after last)
      if (i < sems.length - 1) {
        rule(0.15, [220, 220, 220]);
        gap(2);
      }
    });

    // Totals row
    gap(2);
    rule(0.5, DARK);
    gap(4.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(BLACK[0], BLACK[1], BLACK[2]);
    doc.text("Cumulative GPA",                        COL_NAME,    y);
    doc.text(cgpa !== null ? cgpa.toFixed(3) : "—",  COL_GPA,     y);
    doc.text(cgpa !== null ? shortGrade(cgpa) : "—", COL_GRADE,   y);
    doc.text(String(totalCredits),                    COL_CREDITS, y);
    gap(8);
  }

  // ── CLOSING RULE ──────────────────────────────────────────────────────────
  guard(14);
  rule(0.8, BLACK);
  gap(6);

  // ── CERTIFICATION NOTE ────────────────────────────────────────────────────
  text(
    "This report was generated automatically by GradeIQ and reflects data",
    PAGE_W / 2, { size: 8, color: MID, align: "center" }
  );
  gap(4.5);
  text(
    "entered by the student. It is not an official university transcript.",
    PAGE_W / 2, { size: 8, color: MID, align: "center" }
  );
  gap(6);
  rule(0.3, LIGHT);

  // ── FINAL FOOTER ──────────────────────────────────────────────────────────
  drawFooter();

  // ── SAVE ──────────────────────────────────────────────────────────────────
  const name     = store.userName ? store.userName.replace(/\s+/g, "_") + "_" : "";
  const dateStr  = new Date().toISOString().slice(0, 10);
  doc.save(`GradeIQ_${name}Academic_Report_${dateStr}.pdf`);
}
